# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 834af690d295b5c3ea0dfbe8ae4f7f24de030d6b9feb7df14fe8dd967d33ccf25ff879039d6267016ab918ad9e8752e7e4924fecd4f2f040f6aa0bd2c71ac7a0

test:
  secret_key_base: 1a7aff152efa7d4d9f728028c18ebfe13c6edaba4ecad09d10903b5e93bed169cfaaf63a4d87ccad9228f1d2738d7ce8e2977f5807462dd23ff64396a514fdbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
